# Generated by Django 6.0.3 on 2026-03-05 02:52
# ruff: noqa: E501

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0002_invitation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("cost_plus", "Cost Plus"),
                            ("fixed_price", "Fixed Price"),
                            ("t_m", "Time & Materials"),
                            ("overhead", "Overhead / G&A"),
                            ("leave", "Leave (Vacation/Sick/Holiday)"),
                            ("bid_proposal", "Bid & Proposal (B&P)"),
                            ("ir_d", "IR&D"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_billable", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "code"),
                        name="unique_project_code_per_company",
                    )
                ],
            },
        ),
    ]
