# Generated by Django 6.0.3 on 2026-03-05 03:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0002_invitation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invitation",
            name="role",
        ),
    ]
