# Generated by Django 6.0.3 on 2026-03-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_replace_role_with_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='auto_close_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='auto_open',
            field=models.BooleanField(default=False),
        ),
    ]
