# Generated by Django 6.0.3 on 2026-03-06 14:50
# ruff: noqa: E501

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
        ('companies', '0005_add_auto_close_hours_auto_open'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupApproverRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backup_approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_approver_rules_as_backup', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_approver_rules', to='companies.company')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_approver_rules_as_supervisor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='backupapprover',
            name='source_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backups', to='approvals.backupapproverrule'),
        ),
        migrations.AddConstraint(
            model_name='backupapproverrule',
            constraint=models.UniqueConstraint(fields=('company', 'supervisor', 'backup_approver'), name='unique_backup_approver_rule'),
        ),
    ]
