# Generated by Django 6.0.3 on 2026-03-06 01:26
# ruff: noqa: E501

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0004_replace_role_with_flags"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimePeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly (Mon-Sun)"),
                            ("biweekly", "Bi-Weekly (2 weeks, Mon-Sun)"),
                            ("semimonthly", "Semi-Monthly (1st-15th, 16th-EOM)"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=10,
                    ),
                ),
                (
                    "auto_close_hours",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_periods",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "start_date"), name="unique_period_start"
                    )
                ],
            },
        ),
    ]
