# Generated by Django 6.0.3 on 2026-03-06 14:50
# ruff: noqa: E501

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_add_auto_close_hours_auto_open'),
        ('projects', '0004_remove_old_fields'),
        ('timesheets', '0002_timesheet_timeentry_timesheet_unique_employee_period'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeperiod',
            name='auto_close_hours',
        ),
        migrations.RemoveField(
            model_name='timeperiod',
            name='period_type',
        ),
        migrations.AlterField(
            model_name='timeperiod',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('future', 'Future')], default='future', max_length=10),
        ),
        migrations.CreateModel(
            name='EmployeePreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_presets', to='companies.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_presets', to=settings.AUTH_USER_MODEL)),
                ('labor_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_presets', to='projects.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'employee', 'labor_category'), name='unique_employee_preset')],
            },
        ),
    ]
